apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric-pvc

      containers:
      - name: prometheus
        image: prom/prometheus:latest
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: fabricfiles
          subPath: ./config/prometheus/
        # - mountPath: /etc/hosts
        #   name: fabricfiles
        #   subPath: ./config/hosts
        
