OrdererOrgs:
  - Name: Orderer
    Domain: jwclab.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.jwclab.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.jwclab.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

