apiVersion: v1
kind: Service
metadata:
  name: orderer
  labels:
    run: orderer
spec:
  type: ClusterIP
  selector:
    name: orderer
  ports:
  - protocol: TCP
    port: 31010
    name: grpc
  - protocol: TCP
    port: 8443
    name: prometheus
