apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-explorer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: explorer
  template:
    metadata:
      labels:
        name: explorer
    spec:
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric-pvc
      

      containers:
      - name: explorer
        image: hyperledger/explorer:1.1.1
        env:
        - name: EXTRA_HOST
          value: grafana
        - name: EXTRA_HOST
          value: prometheus
        - name: DATABASE_HOST
          value: blockchain-explorer-db
        - name: DATABASE_DATABASE
          value: fabricexplorer
        - name: DATABASE_USERNAME
          value: hppoc
        - name: DATABASE_PASSWORD
          value: password
        - name: LOG_LEVEL_APP
          value: "debug"
        - name: LOG_LEVEL_DB
          value: "debug"
        - name: LOG_LEVEL_CONSOLE
          value: "info"
        - name: LOG_CONSOLE_STDOUT
          value: "true"
        - name: DISCOVERY_AS_LOCALHOST
          value: "false"
        command: ["sh","-c","node --version && node /opt/explorer/main.js && tail -f /dev/null"]
        volumeMounts:
        - mountPath: /opt/explorer/app/platform/fabric/config.json
          name: fabricfiles
          subPath: ./config/explorer/app/config.json
        - mountPath: /opt/explorer/app/platform/fabric/connection-profile
          name: fabricfiles
          subPath: ./config/explorer/app/connection-profile
        - mountPath: /opt/wallet
          name: fabricfiles
          subPath: ./walletstore
        - mountPath: /tmp/crypto
          name: fabricfiles
          subPath: ./crypto-config
        