apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    run: explorer
spec:
  type: ClusterIP 
  selector:
    name: explorer
  ports:
  - protocol: TCP
    port: 8080
    name: explorer
